ShopNuocHoa_Online/Models/Blog.cs
namespace ShopNuocHoa_Online.Models
{
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Blog")]
    public partial class Blog
    {
        [Key]
        public int MaBlog { get; set; }

        [Required]
        [StringLength(100)]
        [DisplayName("Ảnh")]
        public string Anh { get; set; }

        [Required]
        [StringLength(3000)]
        [DisplayName("Nội dung")]
        public string NoiDung { get; set; }

        [StringLength(250)]
        [DisplayName("Tiêu đề")]
        public string TieuDe { get; set; }
    }
}

ShopNuocHoa_Online/Areas/Admin/Controllers/BlogsController.cs
using ShopNuocHoa_Online.Models;
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ShopNuocHoa_Online.Areas.Admin.Controllers
{
    public class BlogsController : Controller
    {
        private DBShopNuocHoa db = new DBShopNuocHoa();

        // GET: Admin/Blogs
        public ActionResult Index()
        {
            return View(db.Blogs.ToList());
        }

        // GET: Admin/Blogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: Admin/Blogs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaBlog,Anh,NoiDung,TieuDe")] Blog blog)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    blog.Anh = "";
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = Path.GetFileName(f.FileName);
                        string UpLoadFile = Server.MapPath("~/wwwroot/Images/") + FileName;
                        f.SaveAs(UpLoadFile);
                        blog.Anh = FileName;
                    }
                    db.Blogs.Add(blog);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi dữ liệu" + ex.Message;
                return View(blog);
            }
        }

        // GET: Admin/Blogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Admin/Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaBlog,Anh,NoiDung,TieuDe")] Blog blog)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = Path.GetFileName(f.FileName);
                        string UpLoadFile = Server.MapPath("~/wwwroot/Images/") + FileName;
                        f.SaveAs(FileName);
                        blog.Anh = FileName;
                    }
                    db.Entry(blog).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi dữ liệu" + ex.Message;
                return View(blog);
            }
        }

        // GET: Admin/Blogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Admin/Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.Blogs.Find(id);
            try
            {
                db.Blogs.Remove(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi dữ liệu" + ex.Message;
                return View(blog);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopNuocHoa_Online/Areas/Admin/Views/Blogs/Create.cshtml
@model ShopNuocHoa_Online.Models.Blog

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Blogs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Blog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Anh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="~/wwwroot/Images/no-image-news.png" />
                <p><label for="ufile" style="cursor:pointer">Chọn file ảnh</label></p>
                <input name="ImageFile" id="ufile" type="file" style="display:none" onchange="loadFile(event)" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TieuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    var loadFile = function (event) {
        document.getElementById("output").src = URL.createObjectURL(event.target.files[0])
    };
</script>

ShopNuocHoa_Online/Areas/Admin/Views/Blogs/Delete.cshtml
@model ShopNuocHoa_Online.Models.Blog

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Xoá</h2>

<h3>bạn có chắc chắn xoá?</h3>
<div>
    <h4>@Model.TieuDe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Anh)
        </dt>

        <dd>
            @{
                string ImagePath = "~/wwwroot/Images/" + Model.Anh;
            }
            <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="@Url.Content(ImagePath)" />
            @Html.DisplayFor(model => model.Anh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoiDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TieuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TieuDe)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xoá" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>
@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}

ShopNuocHoa_Online/Areas/Admin/Views/Blogs/Details.cshtml
@model ShopNuocHoa_Online.Models.Blog

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chi tiết</h2>

<div>
    <h4>@Model.TieuDe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Anh)
        </dt>

        <dd>
            @{
                string ImagePath = "~/wwwroot/Images/" + Model.Anh;
            }
            <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="@Url.Content(ImagePath)" />
            @Html.DisplayFor(model => model.Anh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoiDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TieuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TieuDe)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Cập nhật", "Edit", new { id = Model.MaBlog }) |
    @Html.ActionLink("Quay lại", "Index")
</p>